# Navien Water Heater ESPHome Configuration
# Converted from tsquared96/esphome-navien to htumanyan/navien
# Board: ESP32 Dev (esp32dev) with TX=19, RX=22

substitutions:
  device_name: my-navien
  friendly_name: "Navien Water Heater"

esphome:
  name: my-navien
  friendly_name: "Navien Water Heater"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Import htumanyan's Navien external component from GitHub
external_components:
  - source: github://htumanyan/navien
    components: [navien]
    refresh: 1d

# Network configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "${device_name}-fallback"
    password: !secret wifi_password

captive_portal:

# Web server for local access
web_server:
  port: 80

# Logging - disable UART logging to avoid conflicts with RS-485
logger:
  level: DEBUG  # Change to INFO after testing
  baud_rate: 0

# Home Assistant API
api:
  encryption:
    key: !secret api_key

# OTA updates
ota:
  - platform: esphome
    password: !secret ota_password

# UART configuration for RS-485 communication
uart:
  tx_pin: GPIO19
  rx_pin: GPIO22
  baud_rate: 19200
  stop_bits: 1
  parity: none
  rx_buffer_size: 8192
  id: navien_uart

# Diagnostic sensors
text_sensor:
  - platform: version
    name: ${friendly_name} ESPHome Version
    hide_timestamp: true
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
    mac_address:
      name: ${friendly_name} Mac

sensor:
  - platform: uptime
    name: ${friendly_name} Uptime
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal

  # Navien water heater sensors
  - platform: navien
    name: ${friendly_name}
    uart_id: navien_uart
    target_temperature:
      name: ${friendly_name} Target Temp
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    inlet_temperature:
      name: ${friendly_name} Inlet Temp
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    outlet_temperature:
      name: ${friendly_name} Outlet Temp
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    water_flow:
      name: ${friendly_name} Water Flow
      filters:
        - lambda: return x / 3.785;
      unit_of_measurement: "GPM"
    water_utilization:
      name: ${friendly_name} Water Capacity
      unit_of_measurement: "%"
    gas_total:
      name: ${friendly_name} Total Gas Usage
      filters:
        - lambda: return x * 9131.0 / 25193.0 / 10.0;
      unit_of_measurement: "Therms"
      accuracy_decimals: 1
    gas_current:
      name: ${friendly_name} Current Gas Usage
      filters:
        - lambda: return x * 3.9680;
      unit_of_measurement: "BTU"
      accuracy_decimals: 1
    conn_status:
      name: ${friendly_name} Connection Status
    recirc_status:
      name: ${friendly_name} Recirculation Status

# Power on/off switch
switch:
  - platform: navien
    name: ${friendly_name} Power

# Status sensor (required by ESPHome API component)
binary_sensor:
  - platform: status
    name: ${friendly_name} Status

# Hot button for recirculation
button:
  - platform: restart
    name: ${friendly_name} Restart
  - platform: navien
    name: ${friendly_name} Hot Button
    id: navien_hot_button

# Climate entity for temperature control
climate:
  - platform: navien
    id: navien_climate
    name: ${friendly_name} Temperature
    visual:
      min_temperature: 98
      max_temperature: 140
      temperature_step: 1
